= Docker

== Builder les images depuis zéro

L'image docker se base sur une debian wheezy.

    docker pull debian:wheezy

Le logiciel OGI se base sur 3 images docker :
  
  * **java8-mysql-tomcat** : comme son nom l'indique contient les logiciels java8, mysql et tomcat. Une configuration minimale est appliqué (utilisateur admin pour musql par exemple)
  * **ogi-base** : configuration des logiciels pour le logiciel (utilisateur mysql, classpath tomcat ...)
  * **ogi** : image finale contenant le logiciel OGI
  
   cd docker
   docker build -t jerep6/java8-mysql-tomcat:1.0 BaseImage/
   docker build -t jerep6/ogi-base:1.0 OGIBase/
   docker build -t jerep6/ogi:4.5.0 OGI/

Le dernier build nécessite l'enveloppe de livraison d'une version d'OGI. Cette enveloppe doit être au même niveau que le Dockerfile et s'appeler OGI
   
   
== Lancer OGI
Pour lancer le logiciel OGI, il suffit d'instancier l'image ogi. Avant cela, il est conseillé de lancer un conteneur afin d'héberger les données (logs, bdd ...)

    docker run --name=data -v /data busybox:buildroot-2014.02
    docker run --rm --volumes-from data -p 50901:3306 -p 50900:8080 -ti jerep6/ogi:4.5.0