DROP TABLE TJ_DIA_CAT;
DROP TABLE TJ_PRP_EQP;
DROP TABLE TJ_PRP_DIA;

DROP TABLE TA_SALE;
DROP TABLE TA_PHOTO;
DROP TABLE TA_ADDRESS;
DROP TABLE TA_DESCRIPTION;
DROP TABLE TA_ROOM;
DROP TABLE TA_PROPERTY_PLOT;
DROP TABLE TA_PROPERTY_LIVABLE;
DROP TABLE TA_PROPERTY_GARAGE;
DROP TABLE TA_PROPERTY_BUILT;
DROP TABLE TA_PROPERTY;
DROP TABLE TA_LABEL;

DROP TABLE TR_EQUIPMENT;
DROP TABLE TR_TYPE;
DROP TABLE TR_CATEGORY;
DROP TABLE TR_DIAGNOSIS
