#!/bin/bash
#Quick and dirty replacement for env variables

PATH_OGI_INSTALL="/app/ogi/"
PATTERN_PATH_TOMCAT_WEBAPPS="/app/tomcat/webapps/"
PATH_TOMCAT_WEBAPPS=$PATTERN_PATH_TOMCAT_WEBAPPS

#log4j file
LOG4J_FILE=$PATH_OGI_INSTALL"resources/log4j2.xml"
sed -i '/.*ref="Console"/d' $LOG4J_FILE
sed -i 's/fileName=".*"/filename="\/data\/logs\/app.log"/g' $LOG4J_FILE
sed -i 's/filePattern=".*"/filePattern="\/data\/logs\/app-%d{yyyy-MM-dd}-%i.log"/g' $LOG4J_FILE


#environment.properties file
ENVIRONMENT_FILE=$PATH_OGI_INSTALL"resources/properties/environment.properties"
sed -i 's/db.showsql.*$/db.showsql = false/g' $ENVIRONMENT_FILE
sed -i 's/document.storage.dir.*$/document.storage.dir =\/data\/ogi\/storage\//g' $ENVIRONMENT_FILE

sed -i 's/partner.acimflo.url.*$/partner.acimflo.url =http:\/\/www.acimflo.com\//g' $ENVIRONMENT_FILE
sed -i 's/partner.acimflo.connect.login.*$/partner.acimflo.connect.login =LOGIN/g' $ENVIRONMENT_FILE
sed -i 's/partner.acimflo.connect.pwd.*$/partner.acimflo.connect.pwd =ENC(tVRkuXCq2urLvxJNs6hpXQ==)/g' $ENVIRONMENT_FILE

sed -i 's/partner.diaporama.url.*$/partner.diaporama.url =http:\/\/192.168.1.70\//g' $ENVIRONMENT_FILE
sed -i 's/partner.diaporama.connect.login.*$/partner.diaporama.connect.login =LOGIN/g' $ENVIRONMENT_FILE
sed -i 's/partner.diaporama.connect.pwd.*$/partner.diaporama.connect.pwd =ENC(tVRkuXCq2urLvxJNs6hpXQ==)/g' $ENVIRONMENT_FILE


sed -i 's/elasticsearch.data.*$/elasticsearch.data=\/data\/ogi\/elasticsearch\/data\//g' $ENVIRONMENT_FILE
sed -i 's/elasticsearch.plugins.*$/elasticsearch.plugins=\/app\/ogi\/elasticsearch\/plugins\//g' $ENVIRONMENT_FILE


#ogi-web
IHM_CONF_FILE=$PATH_TOMCAT_WEBAPPS"ogi-web/js/module/config/config.js"
sed -i 's/API_URL:.*,/API_URL:window.location.protocol+"\/\/"+window.location.hostname+(window.location.port !== "" ? ":"+window.location.port : "")+"\/ogi-ws",/g' $IHM_CONF_FILE


#batchs
ENVIRONMENT_BATCH_FILE=$PATH_OGI_INSTALL"resources/batch/properties/environment-batch.properties"
sed -i 's/db.url.*$/db.url=jdbc:mysql:\/\/localhost:3306\/ogi/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.extraction.file.root.path.*$/seloger.extraction.file.root.path =\/data\/tmp\/seloger\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.host.*$/seloger.ftp.host =seloger.com/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.directory.*$/seloger.ftp.directory =\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.login.*$/seloger.ftp.login =jerep6/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.pwd.*$/seloger.ftp.pwd =123456/g' $ENVIRONMENT_BATCH_FILE

#leboncoin
sed -i 's/leboncoin.extraction.file.root.path.*$/leboncoin.extraction.file.root.path =\/data\/tmp\/leboncoin\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/leboncoin.ftp.host.*$/leboncoin.ftp.host = ftp.ubiflow.net/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.directory.*$/seloger.ftp.directory =\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/leboncoin.ftp.login.*$/leboncoin.ftp.login =ag400081/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/leboncoin.ftp.pwd.*$/leboncoin.ftp.pwd =123456/g' $ENVIRONMENT_BATCH_FILE

SCRIPT_SELOGER=$PATH_OGI_INSTALL"batchs/bin/passerelle-seloger.sh"
sed -i "s/PROPERTIES_PWD/\$OGI_KEY/g" $SCRIPT_SELOGER
sed -i "s/JAVA\=.*$/JAVA\=\/app\/java\/jdk\/bin\/java/g" $SCRIPT_SELOGER

SCRIPT_ACIMFLO=$PATH_OGI_INSTALL"batchs/bin/passerelle-acimflo.sh"
sed -i "s/PROPERTIES_PWD/\$OGI_KEY/g" $SCRIPT_ACIMFLO
sed -i "s/JAVA\=.*$/JAVA\=\/app\/java\/jdk\/bin\/java/g" $SCRIPT_ACIMFLO

SCRIPT_DIAPORAMA=$PATH_OGI_INSTALL"batchs/bin/passerelle-diaporama.sh"
sed -i "s/PROPERTIES_PWD/\$OGI_KEY/g" $SCRIPT_DIAPORAMA
sed -i "s/JAVA\=.*$/JAVA\=\/app\/java\/jdk\/bin\/java/g" $SCRIPT_DIAPORAMA

SCRIPT_LEBONCOIN=$PATH_OGI_INSTALL"batchs/bin/passerelle-leboncoin.sh"
sed -i "s/PROPERTIES_PWD/\$OGI_KEY/g" $SCRIPT_LEBONCOIN
sed -i "s/JAVA\=.*$/JAVA\=\/app\/java\/jdk\/bin\/java/g" $SCRIPT_LEBONCOIN

SCRIPT_ES_INDEX_ALL=$PATH_OGI_INSTALL"batchs/bin/elasticsearch-index_all.sh"
sed -i "s/PROPERTIES_PWD/\$OGI_KEY/g" $SCRIPT_ES_INDEX_ALL
sed -i "s/JAVA\=.*$/JAVA\=\/app\/java\/jdk\/bin\/java/g" $SCRIPT_ES_INDEX_ALL


#log4j file
LOG4J_FILE=$PATH_OGI_INSTALL"resources/batch/log4j2-batchs.xml"
sed -i 's/fileName=".*"/filename="\/data\/logs\/batchs.log"/g' $LOG4J_FILE
sed -i 's/filePattern=".*"/filePattern="\data\/logs\/batchs-%d{yyyy-MM-dd}-%i.log"/g' $LOG4J_FILE