#!/bin/bash

#Tous les chemins doivent finir par un slash

#Avant d'installer copie les anciens fichiers dans ce dossier
ARCHIVE_DIR="/app//ogi/archives/`date +"%Y-%m-%d-%H%M%S"`"
PATH_DELIVERY="/app/ogi/delivery/"
PATH_OGI_INSTALL="/app/ogi/"
PATH_TOMCAT_DIR="/app/tomcat/"
PATH_TOMCAT_WEBAPP=$PATH_TOMCAT_DIR"webapps/"
PATH_SCRIPT_REPLACE="/app/bin/ogi_replace"
ENVELOPPE_NAME="OGI"
OGI_WS_NAME="ogi-ws.war"
OGI_WS_FOLDER="ogi-ws"
OGI_IHM_NAME="ogi-web"
OGI_RESOURCES_NAME="resources"
OGI_BATCHS_NAME="batchs"


#Paramètres renseignés par la ligne de commande
#Faut-il deployer les ressources externes (properties, jasper)
DEPLOY_RESOURCES=false
#Faut-il deployer le war contenant l'API rest
DEPLOY_WS=false
#Faut-il deployer l'IHM angularjs
DEPLOY_IHM=false
#Faut-il deployer les batchs
DEPLOY_BATCHS=false


##### Recup arguments ######
index=0;
while [ -n "$1" ]; do
	case $1 in
		--deploy-ws)
			DEPLOY_WS=true
			;;
		--deploy-ihm)
			DEPLOY_IHM=true
			;;
		--deploy-resources)
			DEPLOY_RESOURCES=true
			;;
		--deploy-batchs)
			DEPLOY_BATCHS=true
			;;
	esac
	shift
done

if [ $DEPLOY_WS = false -a $DEPLOY_IHM = false -a $DEPLOY_RESOURCES = false -a $DEPLOY_BATCHS = false ]; then
	echo "Rien à deployer. Spécifiez au moins un composant à l'aide des options --deploy-ws --deploy-ihm --deploy-resources --deploy-batchs"
	exit 2
fi


#Vérifie que l'enveloppe spécifiée existe
if [ ! -d $PATH_DELIVERY$ENVELOPPE_NAME ]; then
	echo "L'enveloppe n'existe pas"
	exit 3
fi

echo "DEPLOY_RESOURCES=$DEPLOY_RESOURCES"
echo "DEPLOY_WS=$DEPLOY_WS"
echo "DEPLOY_IHM=$DEPLOY_IHM"
echo "DEPLOY_BATCHS=$DEPLOY_BATCHS"
echo "ENVELOPPE_NAME=$ENVELOPPE_NAME"


#Deploy ws war
if [ $DEPLOY_WS = true ]; then
	echo "deploy-ws"
	echo -e "\tCopie du war à partir de l'enveloppe"
	cp $PATH_DELIVERY$ENVELOPPE_NAME/$OGI_WS_NAME $PATH_TOMCAT_WEBAPP$OGI_WS_NAME
fi

#Deploy ihm folder
if [ $DEPLOY_IHM = true ]; then
	echo "deploy-ihm"
	echo -e "\tCopie du dossier à partir de l'enveloppe"
	cp -r $PATH_DELIVERY$ENVELOPPE_NAME/$OGI_IHM_NAME $PATH_TOMCAT_WEBAPP$OGI_IHM_NAME
fi

#Deploy batchs
if [ $DEPLOY_BATCHS = true ]; then
	echo "deploy-batchs"
	echo -e "\tCopie du dossier à partir de l'enveloppe"
	cp -r $PATH_DELIVERY$ENVELOPPE_NAME/$OGI_BATCHS_NAME $PATH_OGI_INSTALL$OGI_BATCHS_NAME
fi

#Deploy resources
if [ $DEPLOY_RESOURCES = true ]; then
	echo "deploy-resources"
	echo -e "\tCopie du dossier à partir de l'enveloppe"
	cp -r $PATH_DELIVERY$ENVELOPPE_NAME/$OGI_RESOURCES_NAME $PATH_OGI_INSTALL$OGI_RESOURCES_NAME
	
	echo -e "\tRemplacement des variables d'environnement"
	$PATH_SCRIPT_REPLACE
fi