#!/bin/bash


docker build -t jerep6/java8-mysql-tomcat docker/BaseImage/
docker build -t jerep6/ogi-base docker/OGIBase/

# Get OGI version
version=$(head -n 1 ogi-parent/ogi-delivery/target/delivery/version.txt)

# Copie de l'enveloppe de livraison dans le dossier du docker file pour l'envoyer au daemon
mkdir -p docker/OGI/delivery
cp -r "ogi-parent/ogi-delivery/target/delivery/OGI-$version" "docker/OGI/delivery/OGI"

# Craft docker image name according to private registry
docker_image_name="192.168.1.7:5000/ogi:$version"

# Build and tag
docker build -t $docker_image_name docker/OGI/

# Send image to private registry
docker push $docker_image_name