#!/bin/bash
#Quick and dirty replacement for env variables

TOMCAT_VERSION=7.0.52

PATH_OGI_INSTALL="/home/jerep6/install/ogi/"
PATTERN_PATH_TOMCAT_WEBAPPS="/home/jerep6/install/apache-tomcat-VERSION/webapps/"
PATH_TOMCAT_WEBAPPS=${PATTERN_PATH_TOMCAT_WEBAPPS/VERSION/$TOMCAT_VERSION}

#log4j file
LOG4J_FILE=$PATH_OGI_INSTALL"resources/log4j2.xml"
sed -i '/.*ref="Console"/d' $LOG4J_FILE
sed -i 's/fileName=".*"/filename="\/home\/jerep6\/install\/ogi\/logs\/app.log"/g' $LOG4J_FILE
sed -i 's/filePattern=".*"/filePattern="\/home\/jerep6\/install\/ogi\/logs\/app-%d{yyyy-MM-dd}-%i.log"/g' $LOG4J_FILE


#environment.properties file
ENVIRONMENT_FILE=$PATH_OGI_INSTALL"resources/properties/environment.properties"
sed -i 's/document.storage.dir.*$/document.storage.dir =\/home\/jerep6\/install\/ogi\/storage\//g' $ENVIRONMENT_FILE

sed -i 's/partner.acimflo.url.*$/partner.acimflo.url =http:\/\/www.acimflo.com\//g' $ENVIRONMENT_FILE
#sed -i 's/partner.acimflo.connect.login.*$/partner.acimflo.connect.login =LOGIN/g' $ENVIRONMENT_FILE
#sed -i 's/partner.acimflo.connect.pwd.*$/partner.acimflo.connect.pwd =ENC(MDP)/g' $ENVIRONMENT_FILE

sed -i 's/partner.diaporama.url.*$/partner.diaporama.url =http:\/\/192.168.1.70\//g' $ENVIRONMENT_FILE
#sed -i 's/partner.diaporama.connect.login.*$/partner.diaporama.connect.login =LOGIN/g' $ENVIRONMENT_FILE
#sed -i 's/partner.diaporama.connect.pwd.*$/partner.diaporama.connect.pwd =ENC(MDP)/g' $ENVIRONMENT_FILE


#ogi-web
IHM_CONF_FILE=$PATH_TOMCAT_WEBAPPS"ogi-web/js/module/config/config.js"
sed -i 's/API_URL:.*,/API_URL:window.location.protocol+"\/\/"+window.location.hostname+(window.location.port !== "" ? ":"+window.location.port : "")+"\/ogi-ws",/g' $IHM_CONF_FILE


#batchs
ENVIRONMENT_BATCH_FILE=$PATH_OGI_INSTALL"resources/batch/properties/environment-batch.properties"
sed -i 's/db.url.*$/db.url=jdbc:mysql:\/\/localhost:3306\/ogi/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.extraction.file.root.path.*$/seloger.extraction.file.root.path =\/home\/jerep6\/install\/ogi\/tmp\/seloger\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.host.*$/seloger.ftp.host =seloger.com/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.directory.*$/seloger.ftp.directory =\//g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.login.*$/seloger.ftp.login =jerep6/g' $ENVIRONMENT_BATCH_FILE
sed -i 's/seloger.ftp.pwd.*$/seloger.ftp.pwd =123456/g' $ENVIRONMENT_BATCH_FILE

SCRIPT_SELOGER=$PATH_OGI_INSTALL"batchs/bin/seloger-passerelle.sh"
sed -i "s/PROPERTIES_PWD/PASSPHRASE/g" $SCRIPT_SELOGER

#log4j file
LOG4J_FILE=$PATH_OGI_INSTALL"resources/batch/log4j2-seloger.xml"
sed -i 's/fileName=".*"/filename="\/home\/jerep6\/install\/ogi\/logs\/batch-seloger.log"/g' $LOG4J_FILE
sed -i 's/filePattern=".*"/filePattern="\/home\/jerep6\/install\/ogi\/logs\/batch-seloger-%d{yyyy-MM-dd}-%i.log"/g' $LOG4J_FILE